### ISSUE TITLE
Problem with large numers

### ISSUE THREAD

**Issue by AleksanderL** [dart-lang/yaml#114]
The lib converts in loadYaml(String yaml) a large numer, eg. 4393685097626700267668050536035 to 4.3936850976267e+30

**Comment by natebosch** [comment]
The `int` type in Dart is a 64 bit signed integer so that is the range of numeric values we can parse with `package:yaml`. If you need to decode numeric data larger than that I'd recommend using strings and then handling the conversion to `BigInt` in user code. We don't have any plans on automatically trying to convert values outside of the 64 bit range (or the JS numeric range when running on the web).
