### ISSUE TITLE
Cannot reread file

### ISSUE THREAD

**Issue by CommanderPaladin** [dart-lang/yaml#116]
When I read an YAML file for the first time, everything is fine.
If I update the file externally during the runtime, the changes won't update on the second reading during the same runtime.

**Comment by natebosch** [comment]
This question appears unrelated to this package which doesn't handle file reading.

> If I update the file externally during the runtime, the changes won't update on the second reading during the same runtime.

Do you mean that a call to `File(filePath).readAsString()` does not return the updated content of the file?

If you can reliably reproduce this behavior please file an issue at https://github.com/dart-lang/sdk/issues

I'm going to close for now since this is not actionable in this repo.
