### ISSUE TITLE
YamlMap does not sport any type parameters

### ISSUE THREAD

**Issue by srawlins** [dart-lang/yaml#38]
This makes it hard to call `forEach`, or other methods that take a callback, without using dynamic as bottom (https://github.com/dart-lang/sdk/issues/29630):

```dart
YamlMap a = ...
a.forEach((String k, YamlMap v) { ... }); // uses dynamic as bottom.
```

**Comment by srawlins** [comment]
Same with YamlList.

**Comment by nex3** [comment]
I don't know if there's much we can do about this... there are no type guarantees about what these values contain. YAML even allows non-string keys. Ultimately, you have to make an assertion at some point that the values are the types you expect, and Dart as a language strongly encourages you to do that explicitly with `as` or [`Map.cast()`](https://api.dartlang.org/dev/2.0.0-dev.30.0/dart-core/Map/cast.html).

**Comment by srawlins** [comment]
Can we not just do:

```dart
class YamlMap<K, V> extends YamlNode with collection.MapMixin<K, V>, UnmodifiableMapMixin
```

?

**Comment by nex3** [comment]
Where would those type parameters ever be instantiated? `YamlMap` is only ever constructed by the YAML parser, which can make no guarantees about the heterogeneity of the objects the mapping contains.

**Comment by srawlins** [comment]
I'm just looking for an implicit cast (another Dart language feature):

```dart
YamlMap<String, YamlMap> a = ...
a.forEach((String k, YamlMap v) { ... });
```

How would you suggest using Map.cast?

**Comment by nex3** [comment]
Implicit/`as` casts on generic types like that are not runtime strong-mode safe unless the type is actually *constructed* with those generic types. It works in Dart 1 semantics, which had to be very lax around reified generics because the type system made it nearly impossible to guarantee that anything stayed reified, but in Dart 2 it will fail. That's why the `cast()` methods are being added: they change the *reified* type arguments that type-check values as they're accessed.

You should write something like:

```dart
var map = /* ... */.cast<String, YamlMap>();
map.forEach((key, value) { ... });
```
