### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by arpit** [dart-lang/yaml#53]
Current parser crashes when trying to load a yaml document with emojis in it.

```
    var emoji = "😃";
    String s = "YAML:  ${emoji} YAML Ain't Markup Language";
    var doc = loadYaml(s);
    print(doc['YAML']);
```

Error:

```
Error on line 1, column 8: Unexpected character.
  ╷
1 │ YAML:  😃 YAML Ain't Markup Language
  │        ^
  ╵

package:yaml/src/parser.dart 50:7    Parser.parse
package:yaml/src/loader.dart 165:37  Loader._loadMapping
package:yaml/src/loader.dart 86:16   Loader._loadNode
package:yaml/src/loader.dart 62:20   Loader._loadDocument
```

**Comment by fawazhussain** [comment]
flutter_emoji is a package which can parse emojis and can be stored as strings for later reference.
[https://pub.dev/packages/flutter_emoji](url)

**Comment by kevmoo** [comment]
I just hit this, too!

**Comment by littoy** [comment]
Any plan to fix this bug?

**Comment by AdrKacz** [comment]
Hello 😊 Thank you for this package!

Any updates on that ? It would great to load emoji !

**Comment by tamcy** [comment]
Just want to add that this is not just an emoji issue, but a more general one.

The yaml package uses `string_scanner` for string parsing, and it mostly utilizes the package's `peekChar` method, which returns the *code unit* of the string in a specific offset. We all know Dart uses UTF-16 in its internal representation, but the implementation of `_isStandardCharacter()` in `scanner.dart` obviously assumes a UTF-32 codepoint be supplied:

https://github.com/dart-lang/yaml/blob/e5984433a2803d5c67ed0abac5891a55040381ee/lib/src/scanner.dart#L1594-L1598

The last line checks for a range between 0x10000 and 0x10FFFF. If my observation is correct, this will never be true because `char` will never be larger than 0xFFFF. So, the actual issue is that the YAML parser doesn't handle surrogate pairs correctly for plain (unquoted) style. This does not only affects emojis. For instance, the following line is fine:

```yaml
char: 兼
```

But the following would yield an "Unexpected character" exception:
```yaml
char: 𠔥
```

Both are CJK characters, parsing would fail for the second case because 𠔥 (U+20525) requires two code units. This is what I have encountered. This requires YAML file author to remember to quote certain characters, or to quote all characters to play safe.

**Comment by kevmoo** [comment]
Maybe a PR to `string_scanner` is the place to start?

**Comment by tamcy** [comment]
[string_scanner](https://pub.dev/packages/string_scanner/changelog) seems fine, and the latest version (1.2.0) also added codepoint scanning which yaml can take advantage of to fix the problem I described. Perhaps after https://github.com/dart-lang/string_scanner/pull/69 is accepted, which make `.peekCodepoint()` API compatible with `.peekChar()`.

On the other hand, while there seems no harm to migrate the yaml package to use codepoint as the scanning unit (but it may cause performance issue), it also seems to me that changes like https://github.com/dart-lang/yaml/pull/125 is already good enough or even inevitable. Here're my points:

1. It is unlikely to produce a malformed utf-16 string inadvertently, and in my opinion it should not be yaml package's responsibility to check against it.
2. I've run some simple test and found that the yaml package doesn't check against an invalid string if it is quoted. So I think the behavior should be the same for unquoted/plain strings.
3. It is still possible for the new `.peekCodepoint()` method to return a surrogate code point if the string is not formed correctly. And because of (2), yaml should still accept it as a part of the string, instead of throwing an invalid character exception. This means that it is still needed to allow the surrogate codepoint range in `Scanner._isStandardCharacter()`. The difference is that we should not remove the last check `(char >= 0x10000 && char <= 0x10FFFF)` if codepoint scanning is to be used.

**Comment by tamcy** [comment]
btw, I saw @kevmoo points to https://yaml.org/spec/1.2-old/spec.html#id2770814 in https://github.com/dart-lang/yaml/pull/125. I've glanced through the doucment. It looks like the pull request isn't accepted because the document clearly excludes surrogate block in the allowed **character** range, so accepting `\xD800-\xDFFF` somehow violates the spec. But as said, currently the value passed into `Scanner._isStandardCharacter().` is actually a  **codepoint**. In this case (or in order to adhere to the spec and fix the issue) bumping `string_scanner` to `1.2.0` and make use of its new codepoint APIs seems the way to go. And maybe leave quoted string checking to the future.
