### ISSUE TITLE
jsonEncode not working

### ISSUE THREAD

**Issue by jaysson** [dart-lang/yaml#90]
```dart
import 'dart:convert';

final yamlDoc = loadYaml(doc);
jsonEncode(yamlDoc);
```
throws
```
Converting object to an encodable object failed: Instance of 'YamlMap'
```

**Comment by rithviknishad** [comment]
This shall work:

```dart
Map yamlAsMap = loadYaml(doc);
jsonEncdode(yamlAsMap);
```

**Comment by jaysson** [comment]
That would only work for top level. Any maps inside still throw the same error.

**Comment by natebosch** [comment]
We could consider adding a `toJson`, but since Yaml can't be round-tripped through JSON I'm not sure if it is a good idea.

Yaml has a superset of the semantics of json - if you have a `YamlMap` with keys of any type other than `String` the encoding would fail.

My preference would be to have authors convert to a `Map<String, Object?>` manually so they can make the decisions about how to handle Data that cannot be represented as JSON.
